name: push action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - secrets: ["CONTENTFUL_SPACE_ID","CONTENTFUL_ACCESS_TOKEN"]
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build, and test
      run: |
        npm install -g yarn
        yarn
        yarn build --if-present
        yarn test
      env:
        CI: true
